// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/glbter/currency-ex/currency/exchanger (interfaces: CurrencyRater)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	exchanger "github.com/glbter/currency-ex/currency/exchanger"
	gomock "github.com/golang/mock/gomock"
)

// MockCurrencyRater is a mock of CurrencyRater interface.
type MockCurrencyRater struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyRaterMockRecorder
}

// MockCurrencyRaterMockRecorder is the mock recorder for MockCurrencyRater.
type MockCurrencyRaterMockRecorder struct {
	mock *MockCurrencyRater
}

// NewMockCurrencyRater creates a new mock instance.
func NewMockCurrencyRater(ctrl *gomock.Controller) *MockCurrencyRater {
	mock := &MockCurrencyRater{ctrl: ctrl}
	mock.recorder = &MockCurrencyRaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyRater) EXPECT() *MockCurrencyRaterMockRecorder {
	return m.recorder
}

// FindRate mocks base method.
func (m *MockCurrencyRater) FindRate(arg0 exchanger.Currency, arg1 time.Time) (exchanger.CurrencyRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRate", arg0, arg1)
	ret0, _ := ret[0].(exchanger.CurrencyRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRate indicates an expected call of FindRate.
func (mr *MockCurrencyRaterMockRecorder) FindRate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRate", reflect.TypeOf((*MockCurrencyRater)(nil).FindRate), arg0, arg1)
}
